spring.application.name=auctionweb
spring.application.name=auctionweb

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/auction_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=YOUR_PASSWORD_HERE

# Automatically creates your @Entity tables
spring.jpa.hibernate.ddl-auto=update